### ISSUE TITLE
Colon missed at end of string

### ISSUE THREAD

**Issue by borgand** [hallettj/zaml#1]
ZAML misses to escape colon at the end of string, which causes problems if this is followed by newline in the dump.

```
irb(main):135:0> hsh = {"a" => "a value:", "b" => "b value"}
=> {"a"=>"a value:", "b"=>"b value"}
irb(main):136:0> puts ZAML.dump(hsh)
--- 
  a: a value:
  b: b value
=> nil
irb(main):137:0> YAML.load ZAML.dump(hsh)
ArgumentError: syntax error on line 1, col 13: `  a: a value:'
  from /usr/local/lib/ruby/1.8/yaml.rb:133:in `load'
  from /usr/local/lib/ruby/1.8/yaml.rb:133:in `load'
  from (irb):137
  from :0
```

**Comment by hallettj** [comment]
Thank you for catching and reporting this.  I just pushed a change that should fix the issue.  We can push out a new gem patch release shortly.

**Comment by hallettj** [comment]
The new gem is out: version 0.1.3.
